# Generated by Django 5.0.6 on 2024-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='thumb',
        ),
        migrations.AddField(
            model_name='filme',
            name='thumb_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('ACAO', 'Ação'), ('ANIMACAO', 'Animação'), ('ANIME', 'Anime'), ('AVENTURA', 'Aventura'), ('CINEMADAARTE', 'Cinema de arte'), ('CHANCHADA', 'Chanchada'), ('COMEDIA', 'Comédia'), ('COMEDIADEACAO', 'Comédia de ação'), ('COMEDIADETERROR', 'Comédia de terror'), ('COMEDIADRAMATICA', 'Comédia dramática'), ('COMEDIAROMANTICA', 'Comédia romântica'), ('DANCA', 'Dança'), ('DOCUMENTARIO', 'Documentário'), ('DOCUFICCAO', 'Docuficção'), ('DRAMA', 'Drama'), ('ESPIONAGEM', 'Espionagem'), ('FAROESTE', 'Faroeste'), ('FANTASIA', 'Fantasia'), ('FANTASIACIENTIFICA', 'Fantasia científica'), ('FICCAOCIENTIFICA', 'Ficção científica'), ('FILMESCOMTRUQUES', 'Filmes com truques'), ('FILMESDEGUERRA', 'Filmes de guerra'), ('MISTERIO', 'Mistério'), ('MUSICAL', 'Musical'), ('FILMEPOLICIAL', 'Filme policial'), ('ROMANCE', 'Romance'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror'), ('THRILLER', 'Thriller'), ('OUTROS', 'Outros')], max_length=30),
        ),
    ]
